version: '4.17'
services:
  mysql5-db:
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # REPLACE "./data" WITH THE PATH TO A LOCAL FOLDER WHERE YOU WANT TO STORE YOUR DB FILES
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: test
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
    ports:
      # IMPORTANT!!!: YOU CAN USE ANY PORT YOU WANT BUT 3306 OR YOU WON'T BE ABLE TO CONNECT TO THE SERVER.
      - 33061:3306

  mysql5-adminer:
    image: adminer
    restart: always
    ports:
      # SET HERE THE PORT YOU WANT TO USE FOR THE WEB MYSQL ADMINER (ej: http://localhost:8080)
      - 8080:8080  
